### ISSUE TITLE
Port to native R support in Travis.

### ISSUE THREAD

**Issue by siddharthab** [Bioconductor/GoogleGenomics#38] opened 2015-05-05 01:37 UTC
https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

I could not see a straight way to use the devel Bioc repo in the new native support. The code is now only compatible with the devel repo and using release Bioc packages will break the vignettes.

**Comment by pgrosu** [comment] 2015-05-05 02:49
So what happens when you do this in Travis with R?

```
library(BiocInstaller) 
useDevel()
```

**Comment by siddharthab** [comment] 2015-05-05 09:20
The documentation for native R support does not tell me how to issue commands within R before it tries to install the packages. There could be a way to do it with before_script but if it is not clean enough, there is no point in porting the current setup to the new one.

**Comment by pgrosu** [comment] 2015-05-05 11:40
Sure you can, with the `r_github_packages` entry where you put your customizations in your repository, and/or separately with the `Rscript` command  like this:

`Rscript -e 'print("Yay :)") ; library(GoogleGenomics)'`

A full example using `r_github_packages` is here:

http://docs.travis-ci.com/user/languages/r/

An example using `Rscript` is here:

https://github.com/craigcitro/r-travis/blob/master/.travis.yml

So you'll notice the following restriction, but you can issue the above commands as necessary:

https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

*The configuration for R builds in Travis is a bit different than this repo: it's a declarative approach, as opposed to the more imperative approach we use with travis-tool.sh. This means that instead of specifying a list of commands to run in a fixed order, you list your dependencies, and the system takes care of the rest. (Under the hood, it's mostly similar code -- we just use it differently.)*

There's always the option of contributing to Travis, though many of our friends would be happy to tweak based on [the following](http://docs.travis-ci.com/user/languages/r/) :)

*Travis CI support for R is contributed by the community and may be removed or altered at any time. If you run into any problems, please report them in the Travis CI issue tracker and cc @craigcitro, @eddelbuettel, and @hadley.*

Hope it helps,
~p

**Comment by craigcitro** [comment] 2015-05-05 17:33
@pgrosu is right, you can sprinkle in whatever commands you want in sections like `before_script`. it's just like the travis config when any other language is set.

we also support the *release* [version of BioC](http://docs.travis-ci.com/user/languages/r/#BioConductor).

at some point, i remember reading that using bioc-devel encouraged you to use R-devel as well. is that no longer the case?

**Comment by siddharthab** [comment] 2015-05-05 17:48
OK if I understand this right, I will have to write the contents of the InstallBiocDeps function from the original script into the before_script operation. This is necessary because the github repo relies on the devel branch of bioc, and not the release. I was hoping to avoid this, but it's not that bad I suppose.

Another complication is that the build and check args rely on whether the run is from a PR or not. I am guessing I can control environment variables like before too without the new syntax.

**Comment by pgrosu** [comment] 2015-05-05 17:51
Thanks @craigcitro :)

**Comment by craigcitro** [comment] 2015-05-05 18:07
@siddharthab actually, i don't think you'll have to reproduce much. 

in fact, there's even an undocumented `bioc_use_devel` function in the r support that probably does what you want ([source](https://github.com/travis-ci/travis-build/blob/502bd1c812f75974cb2f0c5e3bc5381cbb8fbca5/lib/travis/build/script/r.rb#L322)). i just haven't documented it because i haven't really tested it, and because i was worried bioc-devel required R-devel.

just to check: does bioc-devel require R-devel?

**Comment by siddharthab** [comment] 2015-05-05 18:17
Ah perfect!! Thank you.

As for r-devel, it is sometimes recommended but optional. They require a minimum version, and right now it is 3.2.0. http://www.bioconductor.org/developers/how-to/useDevel/.

If you use r-devel, the devel branch of bioc is used by default.

I am perfectly fine with no support for r-devel. It sounded like a nice to have at that point but was not and still not worth the complexity.

**Comment by craigcitro** [comment] 2015-05-05 18:20
ah, that makes sense wrt r-devel.

let me know how the bioc-devel stuff works -- if it all works, i'll document it. :grin:

**Comment by ttriche** [comment] 2015-05-05 18:21
Bioc-devel is targeted at R-devel, yes


--t

**Comment by siddharthab** [comment] 2015-05-07 03:50
I could partially get this to work. But...

Travis runs with native R support seem to be a little unstable. They worked fine on my [fork](https://travis-ci.org/siddharthab/api-client-r/builds/61551878). But the [PR](https://travis-ci.org/googlegenomics/api-client-r/builds/61551979) keeps failing. 1/3 times the step installing the dependent packages was killed, and 2/3 times I get an error: `"The requested ICU resource file cannot be found. Possible problem: ICU data has not been downloaded yet. Call 'stri_install_check()'. (U_FILE_ACCESS_ERROR)"`.

Apart from the instability, the missing functionality is to be able to give different arguments to the build and check commands, based on whether the run is for a PR or not. The reason is that PRs do not have secure environment variables, can not authenticate, and hence can not run the examples. Unless I skip running any code in the examples when not authenticated. Needs some refactoring.

**Comment by pgrosu** [comment] 2015-05-07 04:04
Sid, could you try it by first having it install the package `stringi` in the PR and then proceeding with the rest how you have it.  Let us know if that works.

Thanks,
~p

**Comment by craigcitro** [comment] 2015-05-07 04:06
so it looks like the `stri_install_check` error is an issue with intermittent network connectivity during the `stringi` install -- or, at least, that's what I got from reading hadley/stringr#52. there's a fix listed there that could work, but i think you've got to test it a bit. :confused: 

as to the build vs. test -- i could probably split the steps up in travis, but i bet you don't need much code from [the `script` block](https://github.com/travis-ci/travis-build/blob/502bd1c812f75974cb2f0c5e3bc5381cbb8fbca5/lib/travis/build/script/r.rb#L131). another option would be to support some customizable arguments to the `R CMD build`/`R CMD check` calls -- would that work for you?

**Comment by pgrosu** [comment] 2015-05-07 04:52
Looks like `install.packages("stringi", configure.args="--disable-pkg-config")` might work, otherwise a quick `stri_install_check()` with a followup through `stri_install_icudt()` in case of an issue.  Probably a 10-fold recursion like [exponential backoff](https://code.google.com/p/google-http-java-client/source/browse/google-http-client/src/main/java/com/google/api/client/util/ExponentialBackOff.java?r=79d651502be21122d5950a498604fe4d3f143e4c) :)

~p

**Comment by siddharthab** [comment] 2015-05-08 01:51
@craigcitro I will prefer R_BUILD_ARGS and R_CHECK_ARGS as environment variables so I can have different values for pull requests. The other option is that the new declarative syntax support conditional statements in the definitions, which is an overkill. :)

PS: The [echo](https://github.com/travis-ci/travis-build/blob/502bd1c812f75974cb2f0c5e3bc5381cbb8fbca5/lib/travis/build/script/r.rb#L133) for `build` wrongly uses the env var. The [echo](https://github.com/travis-ci/travis-build/blob/502bd1c812f75974cb2f0c5e3bc5381cbb8fbca5/lib/travis/build/script/r.rb#L144) for `check` is correct.

**Comment by siddharthab** [comment] 2015-05-08 02:01
The `stringi` package is being installed as part of installing `r-cran-devtools`, and so is installed as a binary package. The thread that Craig suggested above has the workaround of using `--disable-pkg-config` as an option to `configure` during source install. The author mentioned this being an issue with the libicu-devel on the system (Suse in that thread) being a very limited bundle. The additional option will compile ICU4C from source instead of relying on the package already in the system.

The workaround for this case is that I will have to manually install stringi again, but this time with the right option as in the thread. Possible to do this in the `before_script` section.

On other thoughts, I retried my run in the fork (not the PR) and it was killed by Travis. That's 2 out of the last 4 runs. I suspect this Travis run is too big now with the default options and using Linux without containers is not going to cut it (takes 25+ mins instead of the 7-9 mins before).

Even if I get the `stringi` issue resolved, I am not going to port this repo to use this feature without reliability. This could mean switching to Mac so that all package dependencies are available as binary, or using containers for Linux builds.

This issue is currently on hold, awaiting progress on https://github.com/travis-ci/travis-ci/issues/3290.

**Comment by gagolews** [comment] 2015-06-24 14:56
This has now been fixed in stringi.

**Comment by pgrosu** [comment] 2015-06-24 15:05
That's great news!  Thank you Marek for helping us with this.

**Comment by siddharthab** [comment] 2015-06-24 15:09
Thank you for letting us know Marek. :)

**Closed** 2017-03-21 02:48 UTC
